# Generated by Django 5.2.8 on 2025-12-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comuna'),
        ),
        migrations.RemoveField(
            model_name='region',
            name='pais',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, choices=[('', 'Selecciona un país'), ('CL', 'Chile')], max_length=2, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Región'),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(default='Y', max_length=200, verbose_name='Nombre de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='password_hash',
            field=models.CharField(default='Y', max_length=128, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='proveedor.categoriaproveedor', verbose_name='Rubros que oferta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
