# Generated by Django 5.2.8 on 2025-12-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_comuna_remove_region_pais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
