# Generated by Django 5.2.5 on 2025-11-23 19:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comerciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('whatsapp', models.CharField(blank=True, help_text='Formato: +569XXXXXXXX', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="El formato debe ser '+569XXXXXXXX'.", regex='^\\+569\\d{8}$')])),
                ('relacion_negocio', models.CharField(choices=[('DUEÑO', 'Dueño/a'), ('ADMIN', 'Administrador/a'), ('EMPLEADO', 'Empleado/a clave'), ('FAMILIAR', 'Familiar a cargo')], max_length=10)),
                ('tipo_negocio', models.CharField(choices=[('ALMACEN', 'Almacén de Barrio'), ('MINIMARKET', 'Minimarket'), ('BOTILLERIA', 'Botillería'), ('PANADERIA', 'Panadería/Pastelería'), ('FERIA', 'Feria Libre'), ('KIOSCO', 'Kiosco'), ('FOODTRUCK', 'Food Truck/Carro de Comida')], max_length=20)),
                ('comuna', models.CharField(max_length=50)),
                ('nombre_negocio', models.CharField(blank=True, default='Mi Negocio Local', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_perfil', models.ImageField(blank=True, default='usuarios/img/default_profile.png', null=True, upload_to='perfiles/')),
                ('intereses', models.CharField(blank=True, default='', help_text='Códigos de intereses separados por coma.', max_length=512)),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos Acumulados')),
                ('nivel_actual', models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino'), ('DIAMANTE', 'Diamante')], default='BRONCE', max_length=50, verbose_name='Nivel de Beneficios')),
                ('rol', models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('PROVEEDOR', 'Proveedor'), ('ADMIN', 'Administrador')], default='COMERCIANTE', max_length=15, verbose_name='Rol de Usuario')),
                ('es_proveedor', models.BooleanField(default=False, verbose_name='Es Proveedor')),
            ],
            options={
                'verbose_name': 'Comerciante',
                'verbose_name_plural': 'Comerciantes',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Beneficio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='beneficios_fotos/', verbose_name='Imagen')),
                ('vence', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('categoria', models.CharField(choices=[('DESCUENTO', 'Descuento y Ofertas'), ('SORTEO', 'Sorteos y Rifas'), ('CAPACITACION', 'Capacitación y Cursos'), ('ACCESO', 'Acceso Exclusivo'), ('EVENTO', 'Eventos Especiales')], default='DESCUENTO', max_length=50, verbose_name='Categoría')),
                ('puntos_requeridos', models.IntegerField(default=0, verbose_name='Puntos Requeridos')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('TERMINADO', 'Terminado'), ('BENEFICIO_ACTIVO', 'Beneficio Reclamado')], default='ACTIVO', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Beneficio y Promoción',
                'verbose_name_plural': 'Beneficios y Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Publicación')),
                ('contenido', models.TextField(verbose_name='Contenido del Post')),
                ('categoria', models.CharField(choices=[('NOTICIAS_CA', 'Noticias Club Almacén'), ('DESPACHOS', 'Despachos realizados'), ('NUEVOS_SOCIOS', 'Nuevos socios'), ('ACTIVIDADES', 'Actividades')], default='NOTICIAS_CA', max_length=50, verbose_name='Categoría')),
                ('imagen_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen/Link de Archivo Subido')),
                ('etiquetas', models.CharField(blank=True, max_length=255, verbose_name='Etiquetas (@usuarios, hashtags)')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='usuarios.comerciante', verbose_name='Comerciante')),
            ],
            options={
                'verbose_name': 'Publicación de Foro',
                'verbose_name_plural': 'Publicaciones de Foro',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_dados', to='usuarios.comerciante', verbose_name='Autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.post', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comerciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dados', to='usuarios.comerciante', verbose_name='Comerciante')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='usuarios.post', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('post', 'comerciante')},
            },
        ),
    ]
