# Generated by Django 5.2.7 on 2025-11-24 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='proveedores/fotos/')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_contacto', models.CharField(blank=True, help_text='Formato: +569XXXXXXXX', max_length=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('ADMIN', 'Administrador')], default='COMERCIANTE', help_text='Define si este usuario es comerciante o administrador del sistema.', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('rubros_ofertados', models.CharField(help_text='Separados por coma', max_length=255, verbose_name='Rubros Ofertados')),
                ('zona_geografica', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='usuarios.proveedor')),
            ],
            options={
                'verbose_name': 'Propuesta de Proveedor',
                'verbose_name_plural': 'Propuestas de Proveedores',
            },
        ),
    ]
