# Generated by Django 5.2.7 on 2025-11-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_comerciante_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comerciante',
            name='rol',
            field=models.CharField(choices=[('COMERCIANTE', 'Comerciante'), ('ADMIN', 'Administrador'), ('PROVEEDOR', 'Proveedor'), ('TECNICO', 'Técnico de soporte')], default='COMERCIANTE', help_text='Define si este usuario es comerciante o administrador del sistema.', max_length=20),
        ),
    ]
