# Generated by Django 5.2.5 on 2025-12-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_comerciante_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='puntos_requeridos',
        ),
        migrations.RemoveField(
            model_name='comerciante',
            name='nivel_actual',
        ),
        migrations.RemoveField(
            model_name='comerciante',
            name='puntos',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
