# Generated by Django 5.2.5 on 2025-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_beneficio_puntos_requeridos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('DUDA', 'Duda / Pregunta'), ('OPINION', 'Opinión / Debate'), ('RECOMENDACION', 'Recomendación'), ('NOTICIA', 'Noticia del Sector'), ('GENERAL', 'General'), ('NOTICIAS_CA', 'Noticias Club Almacén'), ('DESPACHOS', 'Despachos realizados'), ('NUEVOS_SOCIOS', 'Nuevos socios'), ('ACTIVIDADES', 'Actividades en curso')], default='GENERAL', max_length=50, verbose_name='Categoría'),
        ),
    ]
