# Generated by Django 5.2.8 on 2025-12-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_comuna_remove_region_pais_and_more'),
        ('usuarios', '0006_alter_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='proveedor.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
