# Generated by Django 5.2.8 on 2025-12-18 02:33

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0007_alter_propuesta_proveedor_delete_proveedor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comerciante',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='comerciante',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='comerciante',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='comerciante',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='comerciante',
            name='password',
            field=models.CharField(default='y', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comerciante',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='comuna',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='relacion_negocio',
            field=models.CharField(blank=True, choices=[('DUEÑO', 'Dueño/a'), ('ADMIN', 'Administrador/a'), ('EMPLEADO', 'Empleado/a clave'), ('FAMILIAR', 'Familiar a cargo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('ALMACEN', 'Almacén de Barrio'), ('MINIMARKET', 'Minimarket'), ('BOTILLERIA', 'Botillería'), ('PANADERIA', 'Panadería/Pastelería'), ('FERIA', 'Feria Libre'), ('KIOSCO', 'Kiosco'), ('FOODTRUCK', 'Food Truck/Carro de Comida')], max_length=20),
        ),
    ]
