# Generated by Django 5.2.8 on 2025-12-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_comerciante_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comerciante',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
