# Generated by Django 5.2.8 on 2025-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_comerciante_managers_alter_comerciante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comerciante',
            name='password_hash',
            field=models.CharField(default='y', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comerciante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
